#!/usr/bin/env bash
#installs nginx server

sudo apt update
sudo apt install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sed -i '65i add_header X-Served-By 26622-web-01;'
sed -i '66i add_header X-Served-By 26622-web-02;'
sudo service nginx restart