#!/usr/bin/env bash
#installs nginx server

sudo apt update
sudo apt install -y nginx
sed -i '65i add_header X-Served-By 26622-web-01;' /etc/nginx/nginx.conf
sed -i '66i add_header X-Served-By 26622-web-02;' /etc/nginx/nginx.conf
sudo service nginx restart
