#!/usr/bin/env bash
#proxesses and PID file

echo $$ >> /var/run/myscript.pid

term() {
	rm /var/run/holbertonscript.pid
	exit
}

while ((1)) 
do
echo "To infinity and beyond"
trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!" && term()' 2
trap 'term()' 3
done
