#!/usr/bin/env bash
#Configures the ubuntu server
sudo cp /etc/hosts /etc/hosts.old
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.old
sudo sed -i '1 i\8.8.8.8\t\tfacebook.com' /etc/hosts.old
sudo cp /etc/hosts.old /etc/hosts
