#!/usr/bin/env bash
# configure nginx server to run as nginx server
# run on port 8080

sudo sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
sudo service nginx restart
