#!/usr/bin/env bash
# short fix for task 1
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
